### ISSUE TITLE
How to make `seqImg_CKCNN` act causally

### ISSUE THREAD

**Issue by jambo6** [dwromero/ckconv#10]
Hello, 

I've just tried to apply seqImg_CKCNN to a regression task, but the accuracy its achieving indicates the model is not acting causally. Is there something I can change to make the model return causal predictions over the inputs?

In forward method of `CKConv` it runs through `ckconv_f.causal_fftconv(x, conv_kernel, self.bias)`, suggesting it should be acting causally already, but it appears not to be.

Best,
James

**Comment by dwromero** [comment]
Hi James, 

sorry for my last response. Yes, indeed. That should be sufficient. 

Could it perhaps be that you are trying to predict the current value given the previous steps, i.e., `x(t) | [x(t-1). .... x(1)]` and not the future one given the values so far?, i.e., `x(t+1) | [x(t), ... x(1)]`. If this is the case, then the problem would be that the mask is not excluding the current value and thus using simply an identity mapping to solve the task.
