### ISSUE TITLE
There's no 'runs/my_experiment.sh' file and I can't find the argparser part, so is this the final version of the project?

### ISSUE THREAD

**Issue by carry-all-coder** [dwromero/ckconv#2]

**Comment by dwromero** [comment]
Hi carry-all-coder,

Thanks for your question.

Regarding the `run_experiments.sh` files, you can find the commands to replicate our experiments in [https://github.com/dwromero/ckconv/blob/master/runs/runs.md](https://github.com/dwromero/ckconv/blob/master/runs/runs.md). Here we provide all the commands we used in our experiments. We also provide pre-trained models, which you can find in [https://github.com/dwromero/ckconv/tree/master/saved](https://github.com/dwromero/ckconv/tree/master/saved), and evaluate by adding the arguments `--config.train=False --config.pretrained=True` to the corresponding line. I need to change the description in the `README`. Apologies for the confusion.

Regarding the argparsing part, we use [ml_collections](https://github.com/google/ml_collections) for this purpose. The file `config.py` ([https://github.com/dwromero/ckconv/blob/master/config.py](https://github.com/dwromero/ckconv/blob/master/config.py))  specifies the equivalent to the `argparser` arguments.

I hope this helps you further. Please let me know if there are any other questions. 

Thank you for the interest in our work :)

David
