### ISSUE TITLE
No module named 'ckconv.nn'

### ISSUE THREAD

**Issue by jh1234887** [dwromero/ckconv#3]
i tried this code, but not working

`import os,sys
ckconv_source =  os.path.join(os.getcwd(), '..')
if ckconv_source not in sys.path:
    sys.path.append(ckconv_source)

import numpy as np
import torch
from torch.nn.utils import weight_norm
import ckconv
from matplotlib import pyplot as plt
in_channels = 10
out_channels = 10
hidden_channels = 32
activation_function = 'Sine'
norm_type = ''
dim_linear = 1
bias = True
omega_0 = 30.5
weight_dropout = 0.0

ckconv_example = ckconv.CKConv(in_channels,
                              out_channels,
                              hidden_channels,
                              activation_function,
                              norm_type,
                              dim_linear,
                              bias,
                              omega_0,
                              weight_dropout,
                              )`

and then,

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-4bc9e6179833> in <module>
      7 import torch
      8 from torch.nn.utils import weight_norm
----> 9 import ckconv
     10 from matplotlib import pyplot as plt
     11 in_channels = 10

/home/jihye/ckconv/ckconv/__init__.py in <module>
----> 1 from .nn import *
      2 from .utils import *

/home/jihye/ckconv/ckconv/nn/__init__.py in <module>
----> 1 from .activation_functions import Swish, Sine
      2 from .linear import Linear1d, Linear2d
      3 from .norm import LayerNorm
      4 from .ckconv import CKConv, KernelNet
      5 from .ck_block import CKBlock

/home/jihye/ckconv/ckconv/nn/activation_functions.py in <module>
      1 # torch
      2 import torch
----> 3 from ckconv.nn.misc import Expression
      4 
      5 

ModuleNotFoundError: No module named 'ckconv.nn'

what should i do?

**Comment by dwromero** [comment]
Hi! 
Sorry, I just saw this. Were you able to solve the problem?

Best,
David

**Comment by jh1234887** [comment]
Hi i solved that problem. Thanx for your reply

2021년 3월 16일 (화) 오후 5:53, David W. Romero ***@***.***>님이 작성:
