### ISSUE TITLE
Potential applicartion to proteins (long-range interactions)

### ISSUE THREAD

**Issue by hypnopump** [dwromero/ckconv#5]
Hi there!

Very cool work! I'm interested in the potential application of this work to protein structure prediction. I've a repo for doing that with RNNs currently ( https://github.com/hypnopump/rgn2-replica ), and since it's a problem where long-range interactions in sequence space play an important role, I'd like to explore CKCNNs ( I guess they ( https://github.com/dwromero/ckconv/blob/master/models/ckcnn.py#L5 ) could be used as a drop-in replacement for LSTMs here: https://github.com/hypnopump/rgn2-replica/blob/main/rgn2_replica/rgn2.py#L543 )

What do you think? I'd like to read your thoughts on it. 

Sincerely, 
Eric Alcaide

**Comment by dwromero** [comment]
Hi Eric, 

Thank you very much! Indeed. I do think that CKCNNs could be an interesting replacement of RNNs for such tasks. I am very interested in knowing what comes out of it. Please keep me posted :) Yes, I do think that this is the way to change the models. However, if you would like to get more details regarding the model, I am more than happy to schedule a meeting and talk it through. 

Something that might also be interesting is a follow-up work we just released. Our FlexConvs (https://github.com/rjbruin/flexconv) consistently perform better than other sequential methods and achieve SotA results in several tasks. Analogously, you could try it out by replacing the LSTM in your last link, by the model here: https://github.com/rjbruin/flexconv/blob/master/models/cktcn.py#L221 . 

Cheers,
David
