### ISSUE TITLE
Run on Physionet

### ISSUE THREAD

**Issue by ideznaby** [dwromero/ckconv#6]
Hi,
Thank you for this awesome paper and great repository.
I wanted to try this model on MIMIC III and Physionet datasets and I see that there is a physionet.py file in the datasets folder.
If you already tried this on Physionet I would really appreciate it if you can share your code for running it with the configurations you used?

Thanks.

**Comment by dwromero** [comment]
Hi Iman,

Thank you for your kind words. We have indeed. And CKConv seems to work very well as we'll:)

 CKConv gets 0.895 Test AUC in Kidger et al 2020's setting. 

Unfortunately, I am not close to my PC right now. I will make pretrained models as well commands to execute the code online first thing Monday. Does that sounds good?

Cheers,

David

**Comment by ideznaby** [comment]
Great that would be awesome.
I tried running it and ran into some problems so would be great to see your code.

**Comment by dwromero** [comment]
Hi Iman,

I have now modified the repository. Now you can find the execution line used for the PhysioNet experiments, as well as a pretrained checkpoint. This checkpoint should give you a test AUC of 0.8965.

Please let us know if everything works good for you :)

Cheers,
David

**Comment by ideznaby** [comment]
Hi David,
I am getting a test AUC of 0.9310 with this model on Physionet which is higher than what you reported (0.8965).
How did you get that number? Is there anything that I'm missing?

Thanks,
Iman.
