### ISSUE TITLE
kernelnet_omega_0

### ISSUE THREAD

**Issue by flav27** [dwromero/ckconv#8]
What is the 'intuition' about omega values ? Can they be learned as well ?

**Comment by dwromero** [comment]
Hi flav27,

Sorry for my late answer.

**What is the 'intuition' about omega values ?** The intuition behind `w_0` is that it provides a prior on the smoothness of the resulting approximation. To see this, consider a sine function defined as `y = Sin(w_0 * W + b)`. Whereas a low value of `w_0` would lead the output to be smooth, putting this value very high will make the output function oscillate at high frequency. In other words, `w_0` intuitively assigns a prior on the smoothness of the resulting approximations. 

Some examples can be observed in this collab created by the authors of the SIREN paper ( https://colab.research.google.com/github/vsitzmann/siren/blob/master/explore_siren.ipynb ). Here, you will see that good approximations of audio benefit from having a high value of `w_0`, whereas images take advantage of a much lower value. 

**Can they be learned as well ?** In principle they can be learned. However, our experiments indicated that better results are obtained without learning them, and fixing the same `w_0` value to all layers. With that being said, I have the feeling that ckconvs will work better if these `w_0` values are learned in a proper way. However, I have not figured out yet how to do this properly :) 

Please let me know if this is clear and if I can be of any help.

Cheers,
David

**Comment by flav27** [comment]
Thank you for details and congrats with ckconv 👍
